name: pstickers
title: Porangatu Stickers
description: Conheça nossos Stickers
keywords: stickers, adesivos, porangatu
baseurl: "/"
url: ""
timezone: America/Sao_Paulo
locale: pt_BR
encoding: utf-8
status_bar_color: babaca

# Contact Info
address: R 59 A, 429 QUADRA 52 A LOTE 12 | Goiania - GO, 74070-160
phone: (62) 3248-2598
email: porangatustickers@gmail.com
whatsapp: 62999999999
googlemaps: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3880.5086403685996!2d-49.15009008517279!3d-13.442713290548042!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb9584d005bff7d17!2sAssocia%C3%A7%C3%A3o+Comercial+Industrial+e+Agropecu%C3%A1ria+de+Porangatu+-+ACIAP!5e0!3m2!1spt-BR!2sbr!4v1537975308762

# Social
facebook: https://www.facebook.com/pstickerspgtu
instagram: https://www.instagram.com/pstickerspgtu

# Google Analytics
google_analytics_id: UA-123456789

destination: public
source: src

# Server Config options
livereload: true  
reload_port: 5678  

collections:
    pages:
        output: true
        permalink: /:name
    posts:
        output: true
        permalink: /noticias/:name.html

# Pagination 
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules

# assets Compression
assets:
    cache: _assets/_cache
    prefix: "/assets"
    version: true
    compress:
      css: true

    autoprefixer:
        browsers:
          - "last 2 versions"
          - "IE > 9"

    assets:
        - "*.jpg"
        - "*.png"
        - "*.svg"
        - "*.ttf"
        - "*.eot"
        - "*.otf"
        - "*.woff"
        - "*.woff2"
        - "*.pdf"
        - "*.zip"

    sources:
        - _assets
        - _assets/css
        - _assets/img
        - _assets/js

plugins:
    - jekyll-assets
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-redirect-from
    - jekyll-gallery-generator
    - jekyll-paginate

gallery:
  dir: fotos               # Path to the gallery
  symlink: false             # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Fotos"           # Title for gallery index page
  title_prefix: "Fotos da Galeria: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
  sort_reverse: false                          # Possible values are: title, date_time, best_image

  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  # galleries:
  #   chile_trip:
  #     best_image: IMG_1068.JPG  # The image to show on the gallery index page. Defaults to the last image.
  #   japan_trip:
  #     best_image: IMG_0690.JPG
  #     name: "日本の旅"       # Defaults to directory name, replacing _ with spaces & capitalizing words.
  #   awesome_stuff:
  #     best_image: snaileo_gonzales.jpg
  #     sort_reverse: true    # Reverse sort images in gallery.
  #   secret_stuff:
  #     hidden: true          # Don't show this gallery on the index page. People must guess the URL.
  #   with_info:
  #     info:
  #       desc: "Descrição da Galeria" # Info fields can be used in custom templates.

liquid:
  error_mode: lax
